"""
Embedding Fine-Tuning Pipeline — Domain Adaptation for RAG.

The Problem:
  General-purpose embeddings (all-MiniLM-L6-v2) are trained on generic text.
  For specialized domains (legal, medical, finance, code), they miss
  domain-specific vocabulary, acronyms, and semantic relationships.
  Fine-tuning on YOUR data dramatically improves retrieval quality.

The Solution — Contrastive Learning:
  Use triplet/pair data to teach the model:
    "These two texts are semantically similar" (positive pairs)
    "These two texts are NOT similar" (negative pairs)

  Data sources:
    1. User feedback corrections (question, correct_answer, wrong_answer)
    2. Curated (question, relevant_chunk) pairs from your documents
    3. Synthetic pairs generated by LLM from your documents

Training objective:
  MultipleNegativesRankingLoss (MNR): the most effective loss for RAG embedding
  fine-tuning. Each batch item is a (anchor, positive) pair; other positives
  in the batch become the negatives (in-batch negatives).

Output:
  A fine-tuned SentenceTransformer model saved locally.
  Swap EMBEDDING_MODEL in .env to point to the fine-tuned model.

Reference:
  "MTEB: Massive Text Embedding Benchmark" (Muennighoff et al., 2022)
  sentence-transformers training guide: https://sbert.net/docs/training/overview.html
"""

from __future__ import annotations

import json
import logging
import random
from pathlib import Path
from typing import Callable

logger = logging.getLogger(__name__)

FINETUNED_MODEL_DIR = Path("./data/finetuned_embeddings")


# ── Synthetic pair generation from documents ──────────────────────────────────


def generate_synthetic_pairs(
    chunks: list[str],
    llm_fn: Callable[[str], str],
    pairs_per_chunk: int = 2,
) -> list[dict]:
    """
    Generate synthetic (question, answer_chunk) pairs from document chunks.

    For each chunk, ask the LLM to generate questions that the chunk answers.
    These become positive training pairs for fine-tuning.
    This is the most scalable way to get domain-specific training data —
    no human labeling required.

    Args:
        chunks: text chunks from ingested documents
        llm_fn: LLM callable for question generation
        pairs_per_chunk: questions to generate per chunk

    Returns:
        List of {"anchor": question, "positive": chunk_text} dicts
    """
    pairs = []
    for i, chunk in enumerate(chunks):
        if not chunk.strip():
            continue
        prompt = (
            f"Generate {pairs_per_chunk} specific questions that this text directly answers. "
            "Return ONLY the questions, one per line, no numbering.\n\n"
            f"Text: {chunk[:800]}\n\nQuestions:"
        )
        try:
            raw = llm_fn(prompt).strip()
            questions = [q.strip() for q in raw.splitlines() if q.strip() and "?" in q]
            for q in questions[:pairs_per_chunk]:
                pairs.append({"anchor": q, "positive": chunk})
        except Exception as e:
            logger.warning("Synthetic pair generation failed for chunk %d: %s", i, e)

        if i % 20 == 0 and i > 0:
            logger.info("Generated %d synthetic pairs from %d chunks", len(pairs), i + 1)

    logger.info("Total synthetic pairs generated: %d", len(pairs))
    return pairs


# ── Hard negative mining ──────────────────────────────────────────────────────


def mine_hard_negatives(
    pairs: list[dict],
    embed_fn: Callable[[list[str]], list[list[float]]],
    n_negatives: int = 5,
) -> list[dict]:
    """
    Mine hard negatives: chunks that are semantically SIMILAR to the positive
    but are NOT the correct answer. These are the most informative negatives.

    Easy negatives (random irrelevant chunks) don't teach the model much.
    Hard negatives force the model to make fine-grained distinctions.

    For each (anchor, positive) pair:
      1. Embed all positives
      2. Find the K most similar positives to this one
      3. Use those as hard negatives (they're topically similar but wrong)

    Args:
        pairs: list of {"anchor": ..., "positive": ...} dicts
        embed_fn: embedding callable
        n_negatives: hard negatives per pair

    Returns:
        List of {"anchor": ..., "positive": ..., "negative": ...} triplets
    """
    import numpy as np

    if len(pairs) < n_negatives + 1:
        return [{**p, "negative": random.choice([q["positive"] for q in pairs if q != p] or [""])} for p in pairs]

    positives = [p["positive"] for p in pairs]
    logger.info("Mining hard negatives from %d pairs…", len(pairs))

    try:
        embeddings = np.array(embed_fn(positives))

        triplets = []
        for i, pair in enumerate(pairs):
            # Cosine similarities to all other positives
            q_emb = embeddings[i]
            sims = embeddings @ q_emb / (np.linalg.norm(embeddings, axis=1) * np.linalg.norm(q_emb) + 1e-10)
            sims[i] = -1  # exclude self

            # Top-K most similar = hard negatives
            hard_neg_indices = np.argsort(sims)[::-1][:n_negatives]
            for neg_idx in hard_neg_indices:
                triplets.append({
                    "anchor": pair["anchor"],
                    "positive": pair["positive"],
                    "negative": positives[neg_idx],
                })

        logger.info("Mined %d triplets with hard negatives", len(triplets))
        return triplets

    except Exception as e:
        logger.warning("Hard negative mining failed: %s. Using random negatives.", e)
        return [{**p, "negative": random.choice(positives)} for p in pairs]


# ── Training ──────────────────────────────────────────────────────────────────


def finetune_embedding_model(
    training_pairs: list[dict],
    base_model: str = "all-MiniLM-L6-v2",
    output_dir: Path = FINETUNED_MODEL_DIR,
    epochs: int = 3,
    batch_size: int = 32,
    learning_rate: float = 2e-5,
    warmup_ratio: float = 0.1,
    use_mnr_loss: bool = True,
) -> Path:
    """
    Fine-tune a SentenceTransformer model on domain-specific (anchor, positive) pairs.

    Uses MultipleNegativesRankingLoss (MNR) — the state-of-the-art loss for
    embedding fine-tuning. In-batch negatives make training efficient and
    effective without requiring explicit negative mining.

    If triplets (with "negative" key) are provided, falls back to TripletLoss.

    Args:
        training_pairs: list of {"anchor": ..., "positive": ...} or
                        {"anchor": ..., "positive": ..., "negative": ...}
        base_model: HuggingFace model ID to start from
        output_dir: where to save the fine-tuned model
        epochs: training epochs (3-5 is usually enough)
        batch_size: training batch size (larger = more in-batch negatives)
        learning_rate: AdamW learning rate
        warmup_ratio: fraction of steps for linear warmup
        use_mnr_loss: if True, use MNR loss; if False, use Triplet loss

    Returns:
        Path to the saved fine-tuned model directory
    """
    try:
        from sentence_transformers import SentenceTransformer, InputExample
        from sentence_transformers import losses
        from torch.utils.data import DataLoader
    except ImportError as e:
        raise ImportError(
            "sentence-transformers with training support required. "
            "pip install sentence-transformers[train]"
        ) from e

    if not training_pairs:
        raise ValueError("No training pairs provided.")

    output_dir.mkdir(parents=True, exist_ok=True)
    model_path = output_dir / base_model.replace("/", "_")

    logger.info(
        "Fine-tuning '%s' on %d pairs for %d epochs (lr=%.0e)…",
        base_model, len(training_pairs), epochs, learning_rate,
    )

    model = SentenceTransformer(base_model)
    has_negatives = all("negative" in p for p in training_pairs)

    # Build training examples
    if has_negatives and not use_mnr_loss:
        # Triplet loss: (anchor, positive, negative)
        examples = [
            InputExample(texts=[p["anchor"], p["positive"], p["negative"]])
            for p in training_pairs
        ]
        loss = losses.TripletLoss(model=model)
    else:
        # MNR loss: (anchor, positive) — in-batch negatives
        examples = [
            InputExample(texts=[p["anchor"], p["positive"]])
            for p in training_pairs
        ]
        loss = losses.MultipleNegativesRankingLoss(model=model)

    dataloader = DataLoader(examples, shuffle=True, batch_size=batch_size)
    warmup_steps = int(len(dataloader) * epochs * warmup_ratio)

    model.fit(
        train_objectives=[(dataloader, loss)],
        epochs=epochs,
        warmup_steps=warmup_steps,
        optimizer_params={"lr": learning_rate},
        output_path=str(model_path),
        show_progress_bar=True,
    )

    logger.info("Fine-tuned model saved to '%s'", model_path)
    return model_path


# ── Evaluation of fine-tuned model ───────────────────────────────────────────


def evaluate_embedding_model(
    model_path: Path | str,
    test_pairs: list[dict],
    baseline_model: str = "all-MiniLM-L6-v2",
) -> dict:
    """
    Compare fine-tuned model vs baseline on test (question, positive_chunk) pairs.

    Metric: Mean Reciprocal Rank (MRR) and Recall@K.
    For each test pair, rank all positive chunks and check where the correct
    one appears. Higher rank = better retrieval.

    Returns:
        Dict with "baseline_mrr", "finetuned_mrr", "improvement" keys
    """
    try:
        from sentence_transformers import SentenceTransformer
        import numpy as np
    except ImportError:
        return {"error": "sentence-transformers not installed"}

    def compute_mrr(model: SentenceTransformer, pairs: list[dict]) -> float:
        anchors = [p["anchor"] for p in pairs]
        positives = [p["positive"] for p in pairs]
        all_texts = list(set(positives))

        anchor_embs = model.encode(anchors, normalize_embeddings=True)
        corpus_embs = model.encode(all_texts, normalize_embeddings=True)
        text_to_idx = {t: i for i, t in enumerate(all_texts)}

        mrr_total = 0.0
        for i, (anchor_emb, pair) in enumerate(zip(anchor_embs, pairs)):
            sims = corpus_embs @ anchor_emb
            ranked = np.argsort(sims)[::-1]
            correct_idx = text_to_idx[pair["positive"]]
            rank = int(np.where(ranked == correct_idx)[0][0]) + 1
            mrr_total += 1.0 / rank

        return mrr_total / len(pairs)

    baseline = SentenceTransformer(baseline_model)
    finetuned = SentenceTransformer(str(model_path))

    baseline_mrr = compute_mrr(baseline, test_pairs)
    finetuned_mrr = compute_mrr(finetuned, test_pairs)
    improvement = ((finetuned_mrr - baseline_mrr) / baseline_mrr) * 100

    return {
        "baseline_mrr": round(baseline_mrr, 4),
        "finetuned_mrr": round(finetuned_mrr, 4),
        "improvement_pct": round(improvement, 2),
        "n_test_pairs": len(test_pairs),
    }


# ── Full pipeline ─────────────────────────────────────────────────────────────


def run_finetuning_pipeline(
    collection_name: str,
    llm_fn: Callable[[str], str],
    embed_fn: Callable[[list[str]], list[list[float]]],
    use_feedback: bool = True,
    use_synthetic: bool = True,
    epochs: int = 3,
) -> dict:
    """
    End-to-end fine-tuning pipeline:
      1. Collect training data (feedback corrections + synthetic pairs)
      2. Mine hard negatives
      3. Fine-tune the embedding model
      4. Evaluate on a held-out test set

    Returns a summary dict with model path and evaluation metrics.
    """
    from core.ingestion import get_or_create_collection

    training_pairs = []

    # Collect from feedback store
    if use_feedback:
        from core.feedback import get_feedback_store
        store = get_feedback_store()
        contrastive = store.mine_contrastive_pairs(collection_name)
        for cp in contrastive:
            training_pairs.append({"anchor": cp["anchor"], "positive": cp["positive"]})
        logger.info("Collected %d pairs from feedback", len(contrastive))

    # Generate synthetic pairs from documents
    if use_synthetic:
        col = get_or_create_collection(collection_name)
        result = col.get(include=["documents"])
        docs = result.get("documents") or []
        sample = docs[:100]  # limit to 100 chunks to control LLM cost
        synthetic = generate_synthetic_pairs(sample, llm_fn, pairs_per_chunk=2)
        training_pairs.extend(synthetic)
        logger.info("Added %d synthetic pairs", len(synthetic))

    if not training_pairs:
        return {"error": "No training data available. Ingest documents and collect feedback first."}

    # Split 80/20 train/test
    random.shuffle(training_pairs)
    split = int(len(training_pairs) * 0.8)
    train_pairs = training_pairs[:split]
    test_pairs = training_pairs[split:] or training_pairs[:10]

    # Mine hard negatives for training set
    triplets = mine_hard_negatives(train_pairs, embed_fn)

    # Fine-tune
    from config import settings
    model_path = finetune_embedding_model(
        training_pairs=triplets,
        base_model=settings.embedding_model,
        epochs=epochs,
    )

    # Evaluate
    eval_results = evaluate_embedding_model(model_path, test_pairs, settings.embedding_model)

    return {
        "model_path": str(model_path),
        "training_pairs": len(train_pairs),
        "test_pairs": len(test_pairs),
        **eval_results,
    }
